# Generated by Django 2.0.2 on 2018-06-05 16:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20180605_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT', max_length=200)),
                ('system_name', models.CharField(default='DEFAULT', max_length=200)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='Main.Source_Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='source',
            name='folders',
            field=models.ManyToManyField(blank=True, null=True, related_name='sources', to='Main.Source_Folder'),
        ),
    ]
