# Generated by Django 2.0.2 on 2018-06-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20180611_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution_folder',
            name='task_order',
        ),
    ]
