# Generated by Django 2.0.2 on 2018-09-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20180619_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ans',
            field=models.TextField(blank=True),
        ),
    ]
