# Generated by Django 2.0.2 on 2018-09-14 13:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='Main.Source'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subchapters', to='Main.Chapter'),
        ),
    ]
