# Generated by Django 2.0.2 on 2018-09-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20180914_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumber',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasknumbers', to='Main.Chapter'),
            preserve_default=False,
        ),
    ]
