# Generated by Django 2.0.2 on 2018-09-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_tasknumber_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumber',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasknumbers', to='Main.Chapter'),
        ),
    ]
