# Generated by Django 2.0.2 on 2018-09-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20180914_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknumber',
            name='chapter',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasknumbers', to='Main.Chapter'),
        ),
    ]
