# Generated by Django 2.0.2 on 2018-09-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20180916_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknumber',
            name='order',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
