# Generated by Django 2.0.2 on 2018-09-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_tasknumber_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.CharField(blank=True, default='000000', max_length=200, null=True),
        ),
    ]
