# Generated by Django 2.0.2 on 2018-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathattribute',
            name='mathtype',
            field=models.CharField(blank=True, choices=[('Object', 'Объект'), ('Fact', 'Факт'), ('Feature', 'Особенность'), ('TaskType', 'Тип задачи'), ('Method', 'Метод')], max_length=200),
        ),
    ]
