# Generated by Django 2.0.2 on 2018-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_remove_mathattribute_mathtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pic1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
