# Generated by Django 2.0.2 on 2018-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_task_pic1'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pic2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
