# Generated by Django 2.0.2 on 2018-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_task_pic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mpfile1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='mpfile2',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
