# Generated by Django 2.0.2 on 2018-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20181027_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution_folder',
            name='access',
            field=models.BooleanField(default=False),
        ),
    ]
