# Generated by Django 2.0.2 on 2018-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_solution_folder_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mpfile_task',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='task',
            name='pic_task',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
