# Generated by Django 2.0.2 on 2018-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0028_auto_20181029_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='mpfile1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile6',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='mpfile_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic6',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='solution',
            name='pic_sol',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
