# Generated by Django 2.0.2 on 2018-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20181031_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='instruction',
            field=models.TextField(blank=True, default=None),
        ),
    ]
