# Generated by Django 2.0.2 on 2018-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20181106_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.CharField(blank=True, default='000000', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='system_name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mathattribute',
            name='name',
            field=models.CharField(default='DEFAULT_MATHATTRIBUTE_NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mathattribute_folder',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mathattribute_folder',
            name='system_name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='name',
            field=models.CharField(default='DEFAULT_SAVEDFILTER_NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedfilter_folder',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedfilter_folder',
            name='system_name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(default='DEFAULT_SOLUTION_NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution_folder',
            name='name',
            field=models.CharField(default='DEFAULT_FOLDER_NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='solution_folder',
            name='system_name',
            field=models.CharField(default='DEFAULT_FOLDER_SYSTEM_NAME', max_length=1000),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='source_folder',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='source_folder',
            name='system_name',
            field=models.CharField(default='DEFAULT', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tasknumber',
            name='body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tasknumber',
            name='order',
            field=models.CharField(blank=True, default='0', max_length=1000, null=True),
        ),
    ]
