# Generated by Django 2.0.2 on 2018-11-27 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0033_auto_20181111_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Generated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT_TEST_NAME', max_length=1000)),
                ('tasks_order', models.TextField(blank=True, default='{}')),
                ('access', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(blank=True, related_name='test_generateds', to='Main.Task')),
            ],
        ),
    ]
