# Generated by Django 2.0.2 on 2018-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_test_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_generated',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='test_generated',
            name='tasks_order',
            field=models.TextField(blank=True, default=''),
        ),
    ]
