# Generated by Django 2.0.2 on 2018-12-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_auto_20181206_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_template',
            name='access',
        ),
        migrations.RemoveField(
            model_name='test_template',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='test_template',
            name='tasks_order',
        ),
        migrations.AddField(
            model_name='test_template',
            name='folders_and_numbers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
