# Generated by Django 2.0.2 on 2018-12-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0037_auto_20181206_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_template',
            name='tests',
        ),
        migrations.AddField(
            model_name='test_generated',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_generateds', to='Main.Test_Template'),
        ),
    ]
