# Generated by Django 2.0.2 on 2018-12-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_auto_20181206_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_template',
            name='is_permanent',
            field=models.BooleanField(default=True),
        ),
    ]
