# Generated by Django 2.0.2 on 2018-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_test_template_is_permanent'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_template',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
