# Generated by Django 2.0.2 on 2018-12-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0043_star_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star_folder',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='star_folder',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='star_folder',
            name='checkbox_values',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
