# Generated by Django 2.0.2 on 2019-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0044_auto_20181227_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_folder',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='test_folders', to='Main.Test_Generated'),
        ),
    ]
