# Generated by Django 2.0.2 on 2019-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0045_auto_20190122_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_generated',
            name='open_answer',
            field=models.BooleanField(default=False),
        ),
    ]
