# Generated by Django 2.0.2 on 2019-01-31 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0046_test_generated_open_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_generated',
            name='open_answer',
        ),
    ]
