# Generated by Django 2.0.2 on 2019-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0047_remove_test_generated_open_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_generated',
            name='open_answers',
            field=models.BooleanField(default=False),
        ),
    ]
