# Generated by Django 2.0.2 on 2020-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0049_auto_20200420_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedsolimages',
            name='image',
            field=models.ImageField(upload_to='sol_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='uploadedtaskimages',
            name='image',
            field=models.ImageField(upload_to='task_images/%Y/%m/%d/'),
        ),
    ]
