# Generated by Django 2.0.2 on 2020-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0050_auto_20200422_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedsolimages',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedtaskimages',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
