# Generated by Django 2.0.2 on 2020-05-22 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0051_auto_20200430_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.BooleanField(default=False)),
                ('newtask', models.BooleanField(default=False)),
                ('editask', models.BooleanField(default=False)),
                ('solution', models.BooleanField(default=False)),
                ('mathattr', models.BooleanField(default=False)),
                ('source', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.Task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
