# Generated by Django 2.0.2 on 2020-05-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0052_taskchanged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchanged',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
